# Project information
site_name: Radiant Logic DevOps
site_url: https://devops.radiantlogic.com

# Repository
repo_name: radiantlogic-devops/getting-started
repo_url: https://github.com/radiantlogic-devops

# Copyright
copyright: Copyright &copy; 2022 Radiant Logic, Inc.

# Theme
theme:
  name: material
  logo: r1small.jpg
  nav_style: light
  navigation_depth: 5
  features:
    #- navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest    

# Extensions
markdown_extensions:
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

# Page Tree
nav:
- Home: index.md
- Docker: docker.md
- Kubernetes: kubernetes.md
- Helm: helm.md

